app:
  setting:
    mode: "debug"
    cpu_core: 0
  server:

    # listen server addr
    ServerAddr: :8080

    # Maximum duration in millisecond for reading the full request (including body).
    ReadTimeout: 100

    # Maximum duration in millisecond for writing the full response (including body).
    WriteTimeout: 100

    # Per-connection buffer size for requests' reading.
    ReadBufferSize: 4096

    # Per-connection buffer size for responses' writing.
    WriteBufferSize: 4096

    # The maximum number of concurrent connections the server may serve.
    Concurrency: 5000

    # The server will close all the incoming connections after sending
    # the first response to client if this option is set to true.
    DisableKeepalive: false

  auction:
    # global timeout per request in millisecond
    timeout: 100
    dsp:
      node_1:
        # connection type HTTP/GRPC
        type: http
        # timeout on request per dsp in millisecond
        timeout: 1000
        # dsp endpoint
        addr: http://127.0.0.1:8080/bid
      node_2:
        # connection type HTTP/GRPC
        type: http
        # timeout on request per dsp in millisecond
        timeout: 60
        # dsp endpoint
        addr: http://127.0.0.1:8080/bid
      node_3:
        # connection type HTTP/GRPC
        type: http
        # timeout on request per dsp in millisecond
        timeout: 80
        # dsp endpoint
        addr: http://127.0.0.1:8080/bid
